export type SpecialStatus = 
  | 'osnivac'
  | 'upravni_odbor'
  | 'nadzorni_odbor'
  | 'predsednik'
  | 'potpredsednik'
  | 'blagajnik'
  | 'clan'
  | 'drugo';

export interface Member {
  id: number;
  full_name: string;
  email: string;
  quicklook_id: string;
  city: string;
  organization: string;
  phone?: string;
  team?: string;
  status: 'active' | 'pending' | 'inactive';
  special_status: SpecialStatus;
  is_anonymous: boolean;
  /** read-only (generated by DB): NOT is_anonymous */
  readonly is_active_member: boolean;
  consent: boolean;
  agree_join: boolean;
  agree_gdpr: boolean;
  active_participation: boolean;
  send_copy: boolean;
  language: string;
  member_id?: string;
  card_number?: string;
  card_sent: boolean;
  verification_method?: 'email' | 'teams' | 'badge';
  badge_object_path?: string;
  joined_at?: string;
  approved_at?: string;
  approved_by?: string;
  notes?: string;
  created_at: string;
  updated_at: string;
}

export const SPECIAL_STATUS_LABELS: Record<SpecialStatus, { sr: string; en: string }> = {
  osnivac: { sr: 'Osnivač', en: 'Founder' },
  upravni_odbor: { sr: 'Upravni odbor', en: 'Executive Board' },
  nadzorni_odbor: { sr: 'Nadzorni odbor', en: 'Supervisory Board' },
  predsednik: { sr: 'Predsednik', en: 'President' },
  potpredsednik: { sr: 'Potpredsednik', en: 'Vice President' },
  blagajnik: { sr: 'Blagajnik', en: 'Treasurer' },
  clan: { sr: 'Član', en: 'Member' },
  drugo: { sr: 'Drugo', en: 'Other' },
};
